[[redirects]]
  from = "/api/*"
  to = "https://discreet-unrigorously-ophelia.ngrok-free.dev/v1/:splat"
  status = 200
  force = true
  [redirects.headers]
    ngrok-skip-browser-warning = "true"